# Build Python dependencies and frontend assets in a dedicated stage.
FROM python:3.12-slim-bookworm AS build

ARG ESCRIPTORIUM_VERSION=26.04.1
# Select CUDA 12.6 wheels by default; override the index for CPU builds.
ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cu126
ARG TORCH_VERSION=2.7.1
ARG TORCHVISION_VERSION=0.22.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev libxml2-dev libxslt-dev zlib1g-dev \
    libffi-dev libssl-dev git curl \
    libvips && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update && apt-get install -y --no-install-recommends nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/escriptorium

RUN git clone --depth 1 --branch "$ESCRIPTORIUM_VERSION" \
        https://gitlab.com/scripta/escriptorium.git

# Filter optional Passim dependencies alongside TEXT_ALIGNMENT=False below.
RUN pip install --upgrade pip --no-cache-dir && \
    pip install --no-cache-dir \
        "torch==$TORCH_VERSION" "torchvision==$TORCHVISION_VERSION" \
        --index-url "$TORCH_INDEX_URL" && \
    grep -v 'passim' ./escriptorium/app/requirements.txt \
        > /tmp/requirements.txt && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    pip install --no-cache-dir flower gunicorn

RUN cd ./escriptorium/front && \
    npm ci && \
    npm run production && \
    rm -rf node_modules && \
    cd .. && rm -rf .git

# Trim application tests, generated bytecode, and Torch development assets.
RUN find ./escriptorium/app -type d -name tests -prune -exec rm -rf '{}' +
RUN find /usr/local -type d -name __pycache__ -prune -exec rm -rf '{}' +
RUN rm -rf /usr/local/lib/python3.12/site-packages/torch/include \
    /usr/local/lib/python3.12/site-packages/torch/share

# Assemble runtime services with the built Python environment and web assets.
FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    TEXT_ALIGNMENT=False \
    POSTGRES_DB=escriptorium \
    POSTGRES_USER=escriptorium \
    POSTGRES_PASSWORD=escriptorium \
    SQL_PORT=5432

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 libxml2 libxslt1.1 zlib1g libffi8 libssl3 \
    redis postgresql postgresql-contrib \
    libvips42 \
    supervisor nginx && \
    rm -rf /var/lib/apt/lists/*

RUN addgroup --system uwsgi && \
    adduser --system --no-create-home --ingroup uwsgi uwsgi && \
    useradd -ms /bin/bash escriptorium

WORKDIR /home/escriptorium

COPY --from=build /usr/local /usr/local
COPY --from=build --chown=escriptorium:escriptorium /home/escriptorium/escriptorium/app ./escriptorium/app
COPY --from=build --chown=escriptorium:escriptorium /home/escriptorium/escriptorium/front/dist ./escriptorium/front/dist
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY django-init.sh /django-init.sh
COPY docker-entrypoint.sh /usr/local/bin/
COPY nginx.conf /etc/nginx/sites-available/default

RUN chmod +x /django-init.sh /usr/local/bin/docker-entrypoint.sh
RUN find /usr/local -type d -name __pycache__ -prune -exec rm -rf '{}' +

EXPOSE 80 5555

CMD ["docker-entrypoint.sh"]
